---
# tasks file for while_true_do.sys_firewalld

- name: Manage firewalld Packages
  package:
    name: "{{ wtd_sys_firewalld_package }}"
    state: "{{ wtd_sys_firewalld_package_state }}"
  become: true
  tags:
    - firewalld
    - compliance
    - package
    - security
    - system

- name: Manage firewalld Configuration
  template:
    src: "firewalld.conf.j2"
    dest: "/etc/firewalld/firewalld.conf"
  become: true
  notify:
    - Restart firewalld Service
  when:
    - wtd_sys_firewalld_package_state != "absent"
  tags:
    - firewalld
    - compliance
    - configuration
    - security
    - system

- name: Manage firewalld Service
  service:
    name: "{{ wtd_sys_firewalld_service }}"
    state: "{{ wtd_sys_firewalld_service_state }}"
    enabled: "{{ wtd_sys_firewalld_service_enabled }}"
  become: true
  when:
    - ansible_virtualization_type != "docker"
  tags:
    - firewalld
    - compliance
    - service
    - security
    - system

- name: Include firewalld rules tasks
  include_tasks: "{{ item|first }}.yml"
  loop: "{{ wtd_sys_firewalld_rules }}"
  tags:
    - firewalld
    - compliance
    - configuration
    - security
    - system
