---
# tasks file for while_true_do.sys_firewalld

- name: Manage firewalld zone Rich Rule
  firewalld:
    rich_rule: "{{ item.rich_rule }}"
    state: "{{ item.state|default('enabled') }}"
    zone: "{{ item.zone|default('public') }}"
    permanent: true
    immediate: true
  become: true
  tags:
    - firewalld
    - rule
    - security
