---
# tasks file for while_true_do.sys_firewalld

- name: Manage firewalld zone Source
  firewalld:
    source: "{{ item.source }}"
    state: "{{ item.state|default('enabled') }}"
    zone: "{{ item.zone|default('public') }}"
    permanent: true
    immediate: true
  become: true
  tags:
    - firewalld
    - source
    - security
